/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 public/models/office-baked.gltf
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/office-baked.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterSpot" position={[2.44, 2.42, 2.19]} rotation={[Math.PI, -0.72, Math.PI]} scale={5.23}>
          <group name="Armature" position={[0, -0.42, 0]}>
            <primitive object={nodes.Hips} />
            <skinnedMesh name="Wolf3D_Body" geometry={nodes.Wolf3D_Body.geometry} material={nodes.Wolf3D_Body.material} skeleton={nodes.Wolf3D_Body.skeleton} />
            <skinnedMesh name="Wolf3D_Headwear" geometry={nodes.Wolf3D_Headwear.geometry} material={nodes.Wolf3D_Headwear.material} skeleton={nodes.Wolf3D_Headwear.skeleton} />
            <skinnedMesh name="Wolf3D_Outfit_Bottom" geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={nodes.Wolf3D_Outfit_Bottom.material} skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton} />
            <skinnedMesh name="Wolf3D_Outfit_Footwear" geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={nodes.Wolf3D_Outfit_Footwear.material} skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton} />
            <skinnedMesh name="Wolf3D_Outfit_Top" geometry={nodes.Wolf3D_Outfit_Top.geometry} material={nodes.Wolf3D_Outfit_Top.material} skeleton={nodes.Wolf3D_Outfit_Top.skeleton} />
            <skinnedMesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={nodes.EyeLeft.material} skeleton={nodes.EyeLeft.skeleton} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} />
            <skinnedMesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={nodes.EyeRight.material} skeleton={nodes.EyeRight.skeleton} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} />
            <skinnedMesh name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={nodes.Wolf3D_Head.material} skeleton={nodes.Wolf3D_Head.skeleton} morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences} />
            <skinnedMesh name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={nodes.Wolf3D_Teeth.material} skeleton={nodes.Wolf3D_Teeth.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences} />
          </group>
        </group>
        <mesh name="ScreenThreeVideo" geometry={nodes.ScreenThreeVideo.geometry} material={nodes.ScreenThreeVideo.material} position={[1.82, 6.01, -3.25]} />
        <mesh name="ScreenTwoVideo" geometry={nodes.ScreenTwoVideo.geometry} material={nodes.ScreenTwoVideo.material} position={[-1.64, 6.34, -1.73]} rotation={[0, Math.PI / 4, 0]} />
        <mesh name="FirstBook" geometry={nodes.FirstBook.geometry} material={nodes.FirstBook.material} position={[-1.16, 9.31, -4.34]} rotation={[0, 0, -1.76]} />
        <mesh name="FourthBook" geometry={nodes.FourthBook.geometry} material={nodes.FourthBook.material} position={[0.07, 9.23, -4.48]} rotation={[0, -0.17, -1.4]} />
        <group name="LargeDesk" position={[3.76, 2.07, -1.24]}>
          <mesh name="LargeDesk_1" geometry={nodes.LargeDesk_1.geometry} material={nodes.LargeDesk_1.material} />
          <mesh name="LargeDesk_2" geometry={nodes.LargeDesk_2.geometry} material={nodes.LargeDesk_2.material} />
        </group>
        <mesh name="OfficeChair" geometry={nodes.OfficeChair.geometry} material={nodes.OfficeChair.material} position={[2.28, 0.23, 2.06]} rotation={[Math.PI / 2, 0, 2.36]} />
        <mesh name="SecondBook" geometry={nodes.SecondBook.geometry} material={nodes.SecondBook.material} position={[-0.83, 9.25, -4.34]} rotation={[0, 0, -Math.PI / 2]} />
        <group name="SmallDesk" position={[-1.23, 2.07, 4.25]}>
          <mesh name="SmallDesk_1" geometry={nodes.SmallDesk_1.geometry} material={nodes.SmallDesk_1.material} />
          <mesh name="SmallDesk_2" geometry={nodes.SmallDesk_2.geometry} material={nodes.SmallDesk_2.material} />
        </group>
        <group name="SnakePlant" position={[-2.88, 4.38, -2.79]} rotation={[0, 1.56, 0]}>
          <mesh name="SnakePlant_1" geometry={nodes.SnakePlant_1.geometry} material={nodes.SnakePlant_1.material} />
          <mesh name="SnakePlant_2" geometry={nodes.SnakePlant_2.geometry} material={nodes.SnakePlant_2.material} />
          <mesh name="SnakePlant_3" geometry={nodes.SnakePlant_3.geometry} material={nodes.SnakePlant_3.material} />
        </group>
        <mesh name="ThirdBook" geometry={nodes.ThirdBook.geometry} material={nodes.ThirdBook.material} position={[-0.44, 9.24, -4.32]} rotation={[0, 0.11, -Math.PI / 2]} />
        <mesh name="WoodShelf" geometry={nodes.WoodShelf.geometry} material={nodes.WoodShelf.material} position={[1.63, 8.5, -4.13]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Boxer" geometry={nodes.Boxer.geometry} material={nodes.Boxer.material} position={[0.6, 9.09, -4.21]} rotation={[0.05, -0.79, 0.03]} />
        <group name="Keyboard" position={[-0.17, 4.09, -0.05]} rotation={[0, -0.79, 0]}>
          <mesh name="Keyboard_1" geometry={nodes.Keyboard_1.geometry} material={nodes.Keyboard_1.material} />
          <mesh name="Keyboard_2" geometry={nodes.Keyboard_2.geometry} material={nodes.Keyboard_2.material} />
        </group>
        <group name="KeyboardPad" position={[-0.06, 4.01, -0.07]} rotation={[0, -Math.PI / 4, 0]}>
          <mesh name="KeyboardPad_1" geometry={nodes.KeyboardPad_1.geometry} material={nodes.KeyboardPad_1.material} />
          <mesh name="KeyboardPad_2" geometry={nodes.KeyboardPad_2.geometry} material={nodes.KeyboardPad_2.material} />
          <mesh name="KeyboardPad_3" geometry={nodes.KeyboardPad_3.geometry} material={nodes.KeyboardPad_3.material} />
        </group>
        <mesh name="Mouse" geometry={nodes.Mouse.geometry} material={nodes.Mouse.material} position={[1.05, 4.04, -1.48]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} />
        <mesh name="MousePad" geometry={nodes.MousePad.geometry} material={nodes.MousePad.material} position={[1.09, 4.02, -1.4]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} />
        <group name="SpaceMouse" position={[-1.34, 4.19, 1.15]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh name="SpaceMouse_1" geometry={nodes.SpaceMouse_1.geometry} material={nodes.SpaceMouse_1.material} />
          <mesh name="SpaceMouse_2" geometry={nodes.SpaceMouse_2.geometry} material={nodes.SpaceMouse_2.material} />
        </group>
        <group name="3DPrinter" position={[-2.42, 5.28, 5.53]}>
          <mesh name="3DPrinter_1" geometry={nodes['3DPrinter_1'].geometry} material={nodes['3DPrinter_1'].material} />
          <mesh name="3DPrinter_2" geometry={nodes['3DPrinter_2'].geometry} material={nodes['3DPrinter_2'].material} />
          <mesh name="3DPrinter_3" geometry={nodes['3DPrinter_3'].geometry} material={nodes['3DPrinter_3'].material} />
          <mesh name="3DPrinter_4" geometry={nodes['3DPrinter_4'].geometry} material={nodes['3DPrinter_4'].material} />
          <mesh name="3DPrinter_5" geometry={nodes['3DPrinter_5'].geometry} material={nodes['3DPrinter_5'].material} />
          <mesh name="3DPrinter_6" geometry={nodes['3DPrinter_6'].geometry} material={nodes['3DPrinter_6'].material} />
        </group>
        <group name="PlaSpoolBlue" position={[-2.61, 1.02, 5.65]} rotation={[-Math.PI, 0, 0]}>
          <mesh name="PlaSpoolBlue_1" geometry={nodes.PlaSpoolBlue_1.geometry} material={nodes.PlaSpoolBlue_1.material} />
          <mesh name="PlaSpoolBlue_2" geometry={nodes.PlaSpoolBlue_2.geometry} material={nodes.PlaSpoolBlue_2.material} />
        </group>
        <group name="PlaSpoolGreen" position={[-2.61, 0.5, 5.65]} rotation={[-Math.PI, 0, 0]}>
          <mesh name="plaSpoolGreen" geometry={nodes.plaSpoolGreen.geometry} material={nodes.plaSpoolGreen.material} />
          <mesh name="plaSpoolGreen_1" geometry={nodes.plaSpoolGreen_1.geometry} material={nodes.plaSpoolGreen_1.material} />
        </group>
        <group name="PlaSpoolRed" position={[-2.61, 0.84, 4.72]} rotation={[2.06, 0, 0]}>
          <mesh name="plaSpoolRed" geometry={nodes.plaSpoolRed.geometry} material={nodes.plaSpoolRed.material} />
          <mesh name="plaSpoolRed_1" geometry={nodes.plaSpoolRed_1.geometry} material={nodes.plaSpoolRed_1.material} />
        </group>
        <group name="PlaSpoolYellow" position={[-2.61, 0.76, 5.65]} rotation={[-Math.PI, 0, 0]}>
          <mesh name="plaSpoolYellow" geometry={nodes.plaSpoolYellow.geometry} material={nodes.plaSpoolYellow.material} />
          <mesh name="plaSpoolYellow_1" geometry={nodes.plaSpoolYellow_1.geometry} material={nodes.plaSpoolYellow_1.material} />
        </group>
        <group name="Artwork" position={[-4.28, 9.7, 2.87]} rotation={[Math.PI / 2, 1.55, -Math.PI / 2]}>
          <mesh name="Artwork_1" geometry={nodes.Artwork_1.geometry} material={nodes.Artwork_1.material} />
          <mesh name="Artwork_2" geometry={nodes.Artwork_2.geometry} material={nodes.Artwork_2.material} />
        </group>
        <group name="ScreenOne" position={[-3.04, 5.89, 1.9]} rotation={[0, Math.PI / 2, 0]}>
          <mesh name="ScreenOne_1" geometry={nodes.ScreenOne_1.geometry} material={nodes.ScreenOne_1.material} />
          <mesh name="ScreenOne_2" geometry={nodes.ScreenOne_2.geometry} material={nodes.ScreenOne_2.material} />
        </group>
        <group name="ScreenTwo" position={[-1.64, 6.34, -1.73]} rotation={[0, Math.PI / 4, 0]}>
          <mesh name="ScreenTwo_1" geometry={nodes.ScreenTwo_1.geometry} material={nodes.ScreenTwo_1.material} />
          <mesh name="ScreenTwo_2" geometry={nodes.ScreenTwo_2.geometry} material={nodes.ScreenTwo_2.material} />
        </group>
        <mesh name="ScreenThree" geometry={nodes.ScreenThree.geometry} material={nodes.ScreenThree.material} position={[1.82, 6.01, -3.25]} />
        <mesh name="MonitorStand2" geometry={nodes.MonitorStand2.geometry} material={nodes.MonitorStand2.material} position={[-1.72, 5.84, -1.81]} rotation={[0, Math.PI / 4, 0]} />
        <group name="MonitorStand1" position={[-3.69, 5.44, 1.79]} rotation={[0, -0.64, -0.05]}>
          <mesh name="MonitorStand" geometry={nodes.MonitorStand.geometry} material={nodes.MonitorStand.material} />
          <mesh name="MonitorStand_1" geometry={nodes.MonitorStand_1.geometry} material={nodes.MonitorStand_1.material} />
        </group>
        <group name="Office" position={[1.51, 6.23, 1.18]}>
          <mesh name="Office_1" geometry={nodes.Office_1.geometry} material={nodes.Office_1.material} />
          <mesh name="Office_2" geometry={nodes.Office_2.geometry} material={nodes.Office_2.material} />
          <mesh name="Office_3" geometry={nodes.Office_3.geometry} material={nodes.Office_3.material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/office-baked.gltf')
