/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command:npx gltfjsx@6.1.2 public/models/office-baked.gltf
*/

import React from "react";
import { useGLTF, useTexture, useVideoTexture } from "@react-three/drei";
import * as THREE from "three";
import { motion } from "framer-motion-3d";

export function Office(props) {
  const { section } = props;
  const { nodes } = useGLTF(
    "https://res.cloudinary.com/dv6keahg3/image/upload/fl_draco/v1688838830/PortfolioSite/office-baked_jtnms5.gltf"
  );
  const texture = useTexture(
    "https://res.cloudinary.com/dv6keahg3/image/upload/f_auto/q_auto/e_improve:indoor:100/v1688838386/PortfolioSite/office_blsofi.jpg"
  );
  const textureVideo1 = useVideoTexture(
    "https://res.cloudinary.com/dv6keahg3/video/upload/v1688838386/PortfolioSite/screen2_m6bc2q.mp4"
  );
  const textureVideo2 = useVideoTexture(
    "https://res.cloudinary.com/dv6keahg3/video/upload/v1688838386/PortfolioSite/screen1_dbwpe6.mp4"
  );

  texture.flipY = false;

  texture.colorSpace = THREE.SRGBColorSpace;

  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texture,
  });

  return (
    <motion.group
      animate={{ scale: section === 0 ? 1 : 0.25 }}
      {...props}
      dispose={null}
    >
      <mesh
        geometry={nodes.FirstBook.geometry}
        material={textureMaterial}
        position={[-1.16, 9.31, -4.34]}
        rotation={[0, 0, -1.76]}
      />
      <mesh
        geometry={nodes.FourthBook.geometry}
        material={textureMaterial}
        position={[0.07, 9.23, -4.48]}
        rotation={[0, -0.17, -1.4]}
      />
      <motion.group
        animate={{ scale: section === 0 ? 1 : 0.5 }}
        position={[3.76, 2.07, -1.24]}
      >
        <mesh
          geometry={nodes.LargeDesk_1.geometry}
          material={textureMaterial}
        />
        <mesh
          geometry={nodes.LargeDesk_2.geometry}
          material={textureMaterial}
        />
      </motion.group>
      <mesh
        geometry={nodes.OfficeChair.geometry}
        material={textureMaterial}
        position={[2.28, 0.23, 2.06]}
        rotation={[Math.PI / 2, 0, 2.36]}
      />
      <mesh
        geometry={nodes.SecondBook.geometry}
        material={textureMaterial}
        position={[-0.83, 9.25, -4.34]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <group position={[-1.23, 2.07, 4.25]}>
        <mesh
          geometry={nodes.SmallDesk_1.geometry}
          material={textureMaterial}
        />
        <mesh
          geometry={nodes.SmallDesk_2.geometry}
          material={textureMaterial}
        />
      </group>
      <group position={[-2.88, 4.38, -2.79]} rotation={[0, 1.56, 0]}>
        <mesh
          geometry={nodes.SnakePlant_1.geometry}
          material={textureMaterial}
        />
        <mesh
          geometry={nodes.SnakePlant_2.geometry}
          material={textureMaterial}
        />
        <mesh
          geometry={nodes.SnakePlant_3.geometry}
          material={textureMaterial}
        />
      </group>
      <mesh
        geometry={nodes.ThirdBook.geometry}
        material={textureMaterial}
        position={[-0.44, 9.24, -4.32]}
        rotation={[0, 0.11, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.WoodShelf.geometry}
        material={textureMaterial}
        position={[1.63, 8.5, -4.13]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Boxer.geometry}
        material={textureMaterial}
        position={[0.6, 9.09, -4.21]}
        rotation={[0.05, -0.79, 0.03]}
      />
      <group position={[-0.17, 4.09, -0.05]} rotation={[0, -0.79, 0]}>
        <mesh geometry={nodes.Keyboard_1.geometry} material={textureMaterial} />
        <mesh geometry={nodes.Keyboard_2.geometry} material={textureMaterial} />
      </group>
      <group position={[-0.06, 4.01, -0.07]} rotation={[0, -Math.PI / 4, 0]}>
        <mesh
          geometry={nodes.KeyboardPad_1.geometry}
          material={textureMaterial}
        />
        <mesh
          geometry={nodes.KeyboardPad_2.geometry}
          material={textureMaterial}
        />
        <mesh
          geometry={nodes.KeyboardPad_3.geometry}
          material={textureMaterial}
        />
      </group>
      <mesh
        geometry={nodes.Mouse.geometry}
        material={textureMaterial}
        position={[1.05, 4.04, -1.48]}
        rotation={[Math.PI, -Math.PI / 4, Math.PI]}
      />
      <mesh
        geometry={nodes.MousePad.geometry}
        material={textureMaterial}
        position={[1.09, 4.02, -1.4]}
        rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
      />
      <group position={[-1.34, 4.19, 1.15]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh
          geometry={nodes.SpaceMouse_1.geometry}
          material={textureMaterial}
        />
        <mesh
          geometry={nodes.SpaceMouse_2.geometry}
          material={textureMaterial}
        />
      </group>
      <group position={[-2.42, 5.28, 5.53]}>
        <mesh
          geometry={nodes["3DPrinter_1"].geometry}
          material={textureMaterial}
        />
        <mesh
          geometry={nodes["3DPrinter_2"].geometry}
          material={textureMaterial}
        />
        <mesh
          geometry={nodes["3DPrinter_3"].geometry}
          material={textureMaterial}
        />
        <mesh
          geometry={nodes["3DPrinter_4"].geometry}
          material={textureMaterial}
        />
        <mesh
          geometry={nodes["3DPrinter_5"].geometry}
          material={textureMaterial}
        />
        <mesh
          geometry={nodes["3DPrinter_6"].geometry}
          material={textureMaterial}
        />
      </group>
      <group position={[-2.61, 1.02, 5.65]} rotation={[-Math.PI, 0, 0]}>
        <mesh
          geometry={nodes.PlaSpoolBlue_1.geometry}
          material={textureMaterial}
        />
        <mesh
          geometry={nodes.PlaSpoolBlue_2.geometry}
          material={textureMaterial}
        />
      </group>
      <group position={[-2.61, 0.5, 5.65]} rotation={[-Math.PI, 0, 0]}>
        <mesh
          geometry={nodes.plaSpoolGreen.geometry}
          material={textureMaterial}
        />
        <mesh
          geometry={nodes.plaSpoolGreen_1.geometry}
          material={textureMaterial}
        />
      </group>
      <group position={[-2.61, 0.84, 4.72]} rotation={[2.06, 0, 0]}>
        <mesh
          geometry={nodes.plaSpoolRed.geometry}
          material={textureMaterial}
        />
        <mesh
          geometry={nodes.plaSpoolRed_1.geometry}
          material={textureMaterial}
        />
      </group>
      <group position={[-2.61, 0.76, 5.65]} rotation={[-Math.PI, 0, 0]}>
        <mesh
          geometry={nodes.plaSpoolYellow.geometry}
          material={textureMaterial}
        />
        <mesh
          geometry={nodes.plaSpoolYellow_1.geometry}
          material={textureMaterial}
        />
      </group>
      <group
        position={[-4.28, 9.7, 2.87]}
        rotation={[Math.PI / 2, 1.55, -Math.PI / 2]}
      >
        <mesh geometry={nodes.Artwork_1.geometry} material={textureMaterial} />
        <mesh geometry={nodes.Artwork_2.geometry} material={textureMaterial} />
      </group>
      <group position={[-3.04, 5.89, 1.9]} rotation={[0, Math.PI / 2, 0]}>
        <mesh
          geometry={nodes.ScreenOne_1.geometry}
          material={textureMaterial}
        />
        <mesh
          geometry={nodes.ScreenOne_2.geometry}
          material={textureMaterial}
        />
      </group>
      <group position={[-1.64, 6.34, -1.73]} rotation={[0, Math.PI / 4, 0]}>
        <mesh
          geometry={nodes.ScreenTwo_1.geometry}
          material={textureMaterial}
        />
        <mesh
          geometry={nodes.ScreenTwo_2.geometry}
          material={textureMaterial}
        />
      </group>
      <mesh
        geometry={nodes.ScreenThree.geometry}
        material={textureMaterial}
        position={[1.82, 6.01, -3.25]}
      />
      <mesh
        geometry={nodes.MonitorStand2.geometry}
        material={textureMaterial}
        position={[-1.72, 5.84, -1.81]}
        rotation={[0, Math.PI / 4, 0]}
      />
      <group position={[-3.69, 5.44, 1.79]} rotation={[0, -0.64, -0.05]}>
        <mesh
          geometry={nodes.MonitorStand.geometry}
          material={textureMaterial}
        />
        <mesh
          geometry={nodes.MonitorStand_1.geometry}
          material={textureMaterial}
        />
      </group>
      <group position={[1.51, 6.23, 1.18]}>
        <mesh geometry={nodes.Office_1.geometry} material={textureMaterial} />
        <mesh geometry={nodes.Office_2.geometry} material={textureMaterial} />
        <mesh geometry={nodes.Office_3.geometry} material={textureMaterial} />
      </group>
      <mesh
        geometry={nodes.ScreenTwoVideo.geometry}
        position={[-1.64, 6.34, -1.73]}
        rotation={[0, Math.PI / 4, 0]}
      >
        <meshBasicMaterial map={textureVideo2} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.ScreenThreeVideo.geometry}
        position={[1.82, 6.01, -3.25]}
      >
        <meshBasicMaterial map={textureVideo1} toneMapped={false} />
      </mesh>
    </motion.group>
  );
}

useGLTF.preload(
  "https://res.cloudinary.com/dv6keahg3/image/upload/fl_draco/v1688838830/PortfolioSite/office-baked_jtnms5.gltf"
);
